repos:
  - repo: local
    hooks:
      - id: go-fmt-check
        name: go fmt check
        entry: scripts/hooks/go-fmt-check.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: go-mod-tidy-check
        name: go mod tidy check
        entry: scripts/hooks/go-tidy-check.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: go-test
        name: go test
        entry: scripts/hooks/go-test.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: golangci-lint
        name: golangci-lint
        entry: scripts/hooks/go-lint.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert
