package ahm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEscapeCell(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"plain text", "hello", "hello"},
		{"pipe", "a|b", "a\\|b"},
		{"newline", "a\nb", "a b"},
		{"backtick", "a`b", "a\\`b"},
		{"angle brackets", "a<b>c", "a&lt;b&gt;c"},
		{"all special chars", "a|b\nc`d<e>f", "a\\|b c\\`d&lt;e&gt;f"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := escapeCell(tt.input); got != tt.want {
				t.Errorf("escapeCell(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestRenderRootIndexGolden(t *testing.T) {
	index := renderRootIndex([]Task{
		{ID: "001", Title: "Done", Status: "Completed", Priority: "P1", Effort: "S", Labels: "type:task", ExecPlan: "plan-1", Bucket: "completed"},
		{ID: "002", Title: "Ready | Escape", Status: "Pending", Priority: "P0", Effort: "S", Labels: "type:task", ExecPlan: "-", Bucket: "active", DependsOn: []string{"001"}},
		{ID: "003", Title: "Blocked", Status: "Pending", Priority: "P2", Effort: "M", Labels: "type:task", ExecPlan: "-", Bucket: "active", DependsOn: []string{"004"}},
		{ID: "004", Title: "Open Needs Triage", Status: "Open", Priority: "P3", Effort: "L", Labels: "type:task", ExecPlan: "-", Bucket: "active"},
		{ID: "005", Title: "Escaped `<angle>` test", Status: "Pending", Priority: "P2", Effort: "S", Labels: "type:task", ExecPlan: "-", Bucket: "active"},
	})
	assertContainsAll(t, index,
		"# Task Index",
		"- Open: 1",
		"- Pending: 3",
		"- Completed: 1",
		"1. [002](active/002.md) - Ready \\| Escape (P0, S; type:task)",
		"2. [005](active/005.md) - Escaped \\`&lt;angle&gt;\\` test (P2, S; type:task)",
		"| [003](active/003.md) | Blocked | Pending | P2 | M | type:task | - | 004 |",
		"| [004](active/004.md) | Open Needs Triage | Open | P3 | L | type:task | - | - |",
		"| [002](active/002.md) | Ready \\| Escape | Pending | P0 | S | type:task | - | 001 |",
		"| [001](completed/001.md) | Done | Completed | P1 | S | type:task | plan-1 | - |",
		"| [005](active/005.md) | Escaped \\`&lt;angle&gt;\\` test | Pending | P2 | S | type:task | - | - |",
	)
}

func TestRenderBucketIndexGolden(t *testing.T) {
	tasks := []Task{
		{ID: "001", Title: "Active", Status: "Pending", Priority: "P1", Effort: "S", Labels: "type:task", ExecPlan: "-", Bucket: "active"},
		{ID: "002", Title: "Done", Status: "Completed", Priority: "P2", Effort: "M", Labels: "type:task", ExecPlan: "plan-2", Bucket: "completed"},
	}

	assertContainsAll(t, renderBucketIndex(tasks, "active"),
		"# Active Tasks",
		"| [001](001.md) | Active | Pending | P1 | S | type:task | - | - |",
	)
	assertContainsAll(t, renderBucketIndex(tasks, "completed"),
		"# Completed Tasks",
		"| [002](002.md) | Done | Completed | P2 | M | type:task | plan-2 | - |",
	)
	assertContainsAll(t, renderBucketIndex(tasks, "cancelled"),
		"# Cancelled Tasks",
		"None.",
	)
}

func TestRenderResearchIndexGolden(t *testing.T) {
	index := renderResearchIndex(map[string][]markdownDoc{
		"inbox": {
			{Link: "inbox/raw-note.md", Title: "Raw Capture"},
		},
		"investigations": {
			{Link: "investigations/session-review.md", Title: "Session Review"},
		},
		"sources": {},
		"topics": {
			{Link: "topics/index-policy.md", Title: "Index Policy"},
		},
		"archived": {},
	})
	assertContainsAll(t, index,
		"# Research Index",
		"This file is generated by `ahm index`. Do not edit it by hand.",
		"## Inbox",
		"- [Raw Capture](inbox/raw-note.md)",
		"## Investigations",
		"- [Session Review](investigations/session-review.md)",
		"## Sources",
		"No source notes yet.",
		"## Topics",
		"- [Index Policy](topics/index-policy.md)",
		"## Archived",
		"No archived research documents yet.",
	)
}

func TestRenderExecPlanIndexGolden(t *testing.T) {
	index := renderExecPlanIndex("Active ExecPlans", "No active ExecPlans yet.", map[string][]markdownDoc{
		"": {
			{Link: "001-build-indexes.md", Title: "Build Generated Indexes"},
		},
	})
	assertContainsAll(t, index,
		"# Active ExecPlans",
		"This file is generated by `ahm index`. Do not edit it by hand.",
		"- [Build Generated Indexes](001-build-indexes.md)",
	)

	empty := renderExecPlanIndex("Completed ExecPlans", "No completed ExecPlans yet.", map[string][]markdownDoc{"": {}})
	assertContainsAll(t, empty,
		"# Completed ExecPlans",
		"No completed ExecPlans yet.",
	)
}

func TestCollectMarkdownDocsUsesHeadingFallbackAndIgnoresIndex(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".agents", ".research", "topics", "zeta.md"), "# Zeta Topic\n\nBody\n")
	writeFile(t, filepath.Join(root, ".agents", ".research", "topics", "alpha.md"), "No heading here.\n")
	writeFile(t, filepath.Join(root, ".agents", ".research", "topics", "index.md"), "# Ignore Me\n")

	docs, err := collectMarkdownDocs(root, ".agents/.research", []string{"topics"})
	if err != nil {
		t.Fatal(err)
	}
	got := docs["topics"]
	if len(got) != 2 {
		t.Fatalf("docs len = %d, want 2: %#v", len(got), got)
	}
	if got[0] != (markdownDoc{Link: "topics/alpha.md", Title: "alpha"}) {
		t.Fatalf("first doc = %#v", got[0])
	}
	if got[1] != (markdownDoc{Link: "topics/zeta.md", Title: "Zeta Topic"}) {
		t.Fatalf("second doc = %#v", got[1])
	}
}

func TestMainIndexRegeneratesResearchAndExecPlanIndexes(t *testing.T) {
	root := t.TempDir()
	stdout, stderr, code := runCLI(t, "--root", root, "init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	writeFile(t, filepath.Join(root, ".agents", ".research", "investigations", "cli-indexes.md"), "# CLI Indexes\n\nFindings.\n")
	writeFile(t, filepath.Join(root, ".agents", "exec-plans", "active", "generate-indexes.md"), "# Generate Indexes\n\nPlan.\n")
	writeFile(t, filepath.Join(root, ".agents", "exec-plans", "completed", "old-plan.md"), "# Old Plan\n\nDone.\n")
	writeFile(t, filepath.Join(root, ".agents", ".research", "index.md"), "stale\n")

	stdout, stderr, code = runCLI(t, "--root", root, "index")
	if code != 0 {
		t.Fatalf("index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	assertFileContainsAll(t, filepath.Join(root, ".agents", ".research", "index.md"),
		"# Research Index",
		"- [CLI Indexes](investigations/cli-indexes.md)",
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", "exec-plans", "active", "index.md"),
		"# Active ExecPlans",
		"- [Generate Indexes](generate-indexes.md)",
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", "exec-plans", "completed", "index.md"),
		"# Completed ExecPlans",
		"- [Old Plan](old-plan.md)",
	)
}

func TestIndexDryRunReportsOnlyStaleIndexes(t *testing.T) {
	root := t.TempDir()
	cli := func(args ...string) (string, string, int) {
		return runCLI(t, append([]string{"--root", root}, args...)...)
	}

	// Install workflow scaffold.
	stdout, stderr, code := cli("init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Create a task so indexes are non-trivial.
	stdout, stderr, code = cli("task", "create", "Test Task", "--priority", "P1", "--effort", "S")
	if code != 0 {
		t.Fatalf("task create exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Run index so all generated indexes are fresh.
	stdout, stderr, code = cli("index")
	if code != 0 {
		t.Fatalf("index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Case 1: Dry-run after fresh index should produce no output.
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if stdout != "" {
		t.Fatalf("dry-run index after fresh index should be empty, got:\n%s", stdout)
	}

	// Case 2: Stale a generated index and verify dry-run reports it.
	researchIndex := filepath.Join(root, ".agents", ".research", "index.md")
	if err := os.WriteFile(researchIndex, []byte("stale content\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if !strings.Contains(stdout, ".agents/.research/index.md") {
		t.Fatalf("dry-run index should report stale .research/index.md, got:\n%s", stdout)
	}

	// Case 3: Remove a generated index and verify dry-run reports it.
	if err := os.Remove(researchIndex); err != nil {
		t.Fatal(err)
	}
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if !strings.Contains(stdout, ".agents/.research/index.md") {
		t.Fatalf("dry-run index should report missing .research/index.md, got:\n%s", stdout)
	}

	// Case 4: After re-running index, dry-run should be clean again.
	stdout, stderr, code = cli("index")
	if code != 0 {
		t.Fatalf("index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if stdout != "" {
		t.Fatalf("dry-run index after re-index should be empty, got:\n%s", stdout)
	}
}

func TestIndexWithMalformedTaskPrintsWarning(t *testing.T) {
	root := t.TempDir()
	cli := func(args ...string) (string, string, int) {
		return runCLI(t, append([]string{"--root", root}, args...)...)
	}

	// Install workflow scaffold.
	stdout, stderr, code := cli("init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Create a valid task so there's at least one parsed task.
	stdout, stderr, code = cli("task", "create", "Valid Task")
	if code != 0 {
		t.Fatalf("task create exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Write a malformed task file in active/. Use invalid front matter key
	// to trigger a parse error.
	malformed := filepath.Join(root, ".agents", ".tasks", "active", "bad.md")
	if err := os.WriteFile(malformed, []byte("---\ninvalid : key\n---\n# Bad\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Run index — should print warning on stderr and exit 0.
	_, stderr, code = cli("index")
	if code != 0 {
		t.Fatalf("index with malformed task should exit 0, got code %d; stderr=%s", code, stderr)
	}
	if !strings.Contains(stderr, "warning: some task files could not be parsed and were skipped") {
		t.Fatalf("expected warning on stderr, got:\n%s", stderr)
	}
	if !strings.Contains(stderr, "bad.md") {
		t.Fatalf("expected malformed file reference in stderr, got:\n%s", stderr)
	}

	// The valid task should still appear in generated indexes.
	indexPath := filepath.Join(root, ".agents", ".tasks", "index.md")
	assertFileContainsAll(t, indexPath, "Valid Task")
}

func TestIndexWithUnreadableTaskDirAborts(t *testing.T) {
	root := t.TempDir()
	cli := func(args ...string) (string, string, int) {
		return runCLI(t, append([]string{"--root", root}, args...)...)
	}

	// Install workflow scaffold.
	stdout, stderr, code := cli("init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Replace one of the task directories with a regular file so
	// os.ReadDir fails with a non-ErrNotExist error.
	activeDir := filepath.Join(root, ".agents", ".tasks", "active")
	if err := os.RemoveAll(activeDir); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(activeDir, []byte("not a directory\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Run index — should fail because tasks cannot be collected at all.
	stdout, stderr, code = cli("index")
	if code == 0 {
		t.Fatalf("index with unreadable task dir should exit non-zero, got stdout=%s, stderr=%s", stdout, stderr)
	}
	if stderr == "" {
		t.Fatal("expected error on stderr")
	}

	// Generated indexes from init should still exist — failure does not wipe them.
	indexPath := filepath.Join(root, ".agents", ".tasks", "index.md")
	if _, err := os.Stat(indexPath); err != nil {
		t.Fatalf("generated index should be preserved after aborted index: %v", err)
	}
}
