package ahm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderRootIndexGolden(t *testing.T) {
	index := renderRootIndex([]Task{
		{ID: "001", Title: "Done", Status: "Completed", Priority: "P1", Effort: "S", Labels: "type:task", ExecPlan: "plan-1", Bucket: "completed"},
		{ID: "002", Title: "Ready | Escape", Status: "Pending", Priority: "P0", Effort: "S", Labels: "type:task", ExecPlan: "-", Bucket: "active", DependsOn: []string{"001"}},
		{ID: "003", Title: "Blocked", Status: "Pending", Priority: "P2", Effort: "M", Labels: "type:task", ExecPlan: "-", Bucket: "active", DependsOn: []string{"004"}},
		{ID: "004", Title: "Open Needs Triage", Status: "Open", Priority: "P3", Effort: "L", Labels: "type:task", ExecPlan: "-", Bucket: "active"},
	})
	assertContainsAll(t, index,
		"# Task Index",
		"- Open: 1",
		"- Pending: 2",
		"- Completed: 1",
		"1. [002](active/002.md) - Ready | Escape (P0, S; type:task)",
		"| [003](active/003.md) | Blocked | Pending | P2 | M | type:task | - | 004 |",
		"| [004](active/004.md) | Open Needs Triage | Open | P3 | L | type:task | - | - |",
		"| [002](active/002.md) | Ready \\| Escape | Pending | P0 | S | type:task | - | 001 |",
		"| [001](completed/001.md) | Done | Completed | P1 | S | type:task | plan-1 | - |",
	)
}

func TestRenderBucketIndexGolden(t *testing.T) {
	tasks := []Task{
		{ID: "001", Title: "Active", Status: "Pending", Priority: "P1", Effort: "S", Labels: "type:task", ExecPlan: "-", Bucket: "active"},
		{ID: "002", Title: "Done", Status: "Completed", Priority: "P2", Effort: "M", Labels: "type:task", ExecPlan: "plan-2", Bucket: "completed"},
	}

	assertContainsAll(t, renderBucketIndex(tasks, "active"),
		"# Active Tasks",
		"| [001](001.md) | Active | Pending | P1 | S | type:task | - | - |",
	)
	assertContainsAll(t, renderBucketIndex(tasks, "completed"),
		"# Completed Tasks",
		"| [002](002.md) | Done | Completed | P2 | M | type:task | plan-2 | - |",
	)
	assertContainsAll(t, renderBucketIndex(tasks, "cancelled"),
		"# Cancelled Tasks",
		"None.",
	)
}

func TestRenderResearchIndexGolden(t *testing.T) {
	index := renderResearchIndex(map[string][]markdownDoc{
		"inbox": {
			{Link: "inbox/raw-note.md", Title: "Raw Capture"},
		},
		"investigations": {
			{Link: "investigations/session-review.md", Title: "Session Review"},
		},
		"sources": {},
		"topics": {
			{Link: "topics/index-policy.md", Title: "Index Policy"},
		},
		"archived": {},
	})
	assertContainsAll(t, index,
		"# Research Index",
		"This file is generated by `ahm index`. Do not edit it by hand.",
		"## Inbox",
		"- [Raw Capture](inbox/raw-note.md)",
		"## Investigations",
		"- [Session Review](investigations/session-review.md)",
		"## Sources",
		"No source notes yet.",
		"## Topics",
		"- [Index Policy](topics/index-policy.md)",
		"## Archived",
		"No archived research documents yet.",
	)
}

func TestRenderExecPlanIndexGolden(t *testing.T) {
	index := renderExecPlanIndex("Active ExecPlans", "No active ExecPlans yet.", map[string][]markdownDoc{
		"": {
			{Link: "001-build-indexes.md", Title: "Build Generated Indexes"},
		},
	})
	assertContainsAll(t, index,
		"# Active ExecPlans",
		"This file is generated by `ahm index`. Do not edit it by hand.",
		"- [Build Generated Indexes](001-build-indexes.md)",
	)

	empty := renderExecPlanIndex("Completed ExecPlans", "No completed ExecPlans yet.", map[string][]markdownDoc{"": {}})
	assertContainsAll(t, empty,
		"# Completed ExecPlans",
		"No completed ExecPlans yet.",
	)
}

func TestCollectMarkdownDocsUsesHeadingFallbackAndIgnoresIndex(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".agents", ".research", "topics", "zeta.md"), "# Zeta Topic\n\nBody\n")
	writeFile(t, filepath.Join(root, ".agents", ".research", "topics", "alpha.md"), "No heading here.\n")
	writeFile(t, filepath.Join(root, ".agents", ".research", "topics", "index.md"), "# Ignore Me\n")

	docs, err := collectMarkdownDocs(root, ".agents/.research", []string{"topics"})
	if err != nil {
		t.Fatal(err)
	}
	got := docs["topics"]
	if len(got) != 2 {
		t.Fatalf("docs len = %d, want 2: %#v", len(got), got)
	}
	if got[0] != (markdownDoc{Link: "topics/alpha.md", Title: "alpha"}) {
		t.Fatalf("first doc = %#v", got[0])
	}
	if got[1] != (markdownDoc{Link: "topics/zeta.md", Title: "Zeta Topic"}) {
		t.Fatalf("second doc = %#v", got[1])
	}
}

func TestMainIndexRegeneratesResearchAndExecPlanIndexes(t *testing.T) {
	root := t.TempDir()
	stdout, stderr, code := runCLI(t, "--root", root, "init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	writeFile(t, filepath.Join(root, ".agents", ".research", "investigations", "cli-indexes.md"), "# CLI Indexes\n\nFindings.\n")
	writeFile(t, filepath.Join(root, ".agents", "exec-plans", "active", "generate-indexes.md"), "# Generate Indexes\n\nPlan.\n")
	writeFile(t, filepath.Join(root, ".agents", "exec-plans", "completed", "old-plan.md"), "# Old Plan\n\nDone.\n")
	writeFile(t, filepath.Join(root, ".agents", ".research", "index.md"), "stale\n")

	stdout, stderr, code = runCLI(t, "--root", root, "index")
	if code != 0 {
		t.Fatalf("index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	assertFileContainsAll(t, filepath.Join(root, ".agents", ".research", "index.md"),
		"# Research Index",
		"- [CLI Indexes](investigations/cli-indexes.md)",
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", "exec-plans", "active", "index.md"),
		"# Active ExecPlans",
		"- [Generate Indexes](generate-indexes.md)",
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", "exec-plans", "completed", "index.md"),
		"# Completed ExecPlans",
		"- [Old Plan](old-plan.md)",
	)
}

func TestIndexDryRunReportsOnlyStaleIndexes(t *testing.T) {
	root := t.TempDir()
	cli := func(args ...string) (string, string, int) {
		return runCLI(t, append([]string{"--root", root}, args...)...)
	}

	// Install workflow scaffold.
	stdout, stderr, code := cli("init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Create a task so indexes are non-trivial.
	stdout, stderr, code = cli("task", "create", "Test Task", "--priority", "P1", "--effort", "S")
	if code != 0 {
		t.Fatalf("task create exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Run index so all generated indexes are fresh.
	stdout, stderr, code = cli("index")
	if code != 0 {
		t.Fatalf("index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Case 1: Dry-run after fresh index should produce no output.
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if stdout != "" {
		t.Fatalf("dry-run index after fresh index should be empty, got:\n%s", stdout)
	}

	// Case 2: Stale a generated index and verify dry-run reports it.
	researchIndex := filepath.Join(root, ".agents", ".research", "index.md")
	if err := os.WriteFile(researchIndex, []byte("stale content\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if !strings.Contains(stdout, ".agents/.research/index.md") {
		t.Fatalf("dry-run index should report stale .research/index.md, got:\n%s", stdout)
	}

	// Case 3: Remove a generated index and verify dry-run reports it.
	if err := os.Remove(researchIndex); err != nil {
		t.Fatal(err)
	}
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if !strings.Contains(stdout, ".agents/.research/index.md") {
		t.Fatalf("dry-run index should report missing .research/index.md, got:\n%s", stdout)
	}

	// Case 4: After re-running index, dry-run should be clean again.
	stdout, stderr, code = cli("index")
	if code != 0 {
		t.Fatalf("index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	stdout, stderr, code = cli("--dry-run", "index")
	if code != 0 {
		t.Fatalf("dry-run index exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	if stdout != "" {
		t.Fatalf("dry-run index after re-index should be empty, got:\n%s", stdout)
	}
}
