package ahm

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/travisennis/ahm/internal/templates"
)

func TestReadWorkflowFile_CRLF(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "test.md")

	// Write a file with CRLF line endings.
	content := "---\r\nid: 001\r\ntitle: CRLF Task\r\n---\r\n# CRLF Task\r\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	data, err := readWorkflowFile(path)
	if err != nil {
		t.Fatalf("readWorkflowFile: %v", err)
	}

	// Verify CRLF was normalized to LF.
	if strings.Contains(string(data), "\r\n") {
		t.Fatalf("readWorkflowFile did not normalize CRLF: %q", data)
	}
	if !strings.HasPrefix(string(data), "---\n") {
		t.Fatalf("expected LF front matter marker, got: %q", data)
	}
	if !strings.Contains(string(data), "\n---\n") {
		t.Fatalf("expected LF front matter end marker, got: %q", data)
	}
}

func TestReadWorkflowFile_BOM(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "test.md")

	// Write a file with UTF-8 BOM and CRLF line endings.
	// BOM = 0xEF 0xBB 0xBF = "\xef\xbb\xbf"
	bom := "\xef\xbb\xbf"
	content := bom + "---\r\nid: 001\r\ntitle: BOM Task\r\n---\r\n# BOM Task\r\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	data, err := readWorkflowFile(path)
	if err != nil {
		t.Fatalf("readWorkflowFile: %v", err)
	}

	// Verify BOM was stripped and CRLF was normalized to LF.
	if strings.Contains(string(data), "\r\n") {
		t.Fatalf("readWorkflowFile did not normalize CRLF: %q", data)
	}
	if !strings.HasPrefix(string(data), "---\n") {
		t.Fatalf("expected LF front matter marker after BOM strip, got: %q", data)
	}
	if strings.HasPrefix(string(data), "\xef\xbb\xbf") {
		t.Fatalf("BOM was not stripped: %q", data)
	}
}

func TestInstallDryRunPreviewsAllWrites(t *testing.T) {
	root := t.TempDir()
	var out strings.Builder
	a := app{opts: options{root: root, dryRun: true}, out: &out}
	if err := a.install(false); err != nil {
		t.Fatal(err)
	}

	got := out.String()
	for _, want := range []string{
		"created:",
		"  AGENTS.md",
		"directories:",
		"  .agents/.tasks/active",
		"metadata:",
		"  .agents/ahm.json",
		"indexes:",
		"  .agents/.tasks/active/index.md",
		"  .agents/.tasks/cancelled/index.md",
		"  .agents/.tasks/completed/index.md",
		"  .agents/.tasks/index.md",
		"  .agents/.research/index.md",
		"  .agents/exec-plans/active/index.md",
		"  .agents/exec-plans/completed/index.md",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("dry-run output missing %q:\n%s", want, got)
		}
	}
	if _, err := os.Stat(filepath.Join(root, ".agents")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("dry-run wrote .agents directory, err = %v", err)
	}
}

func TestInstallDryRunDoesNotMutateMetadata(t *testing.T) {
	root := t.TempDir()
	oldVersion := "0.0.1"
	initialMeta := metadata{
		Version: oldVersion,
		Files: map[string]string{
			".agents/TASKS.md": "abc123",
			".agents/PLANS.md": "def456",
		},
	}
	if err := writeMetadata(root, initialMeta); err != nil {
		t.Fatal(err)
	}
	metaPath := filepath.Join(root, ".agents", "ahm.json")
	before, err := os.ReadFile(metaPath)
	if err != nil {
		t.Fatal(err)
	}

	var out strings.Builder
	a := app{opts: options{root: root, dryRun: true}, out: &out}
	if err := a.install(false); err != nil {
		t.Fatal(err)
	}

	// Metadata on disk must be unchanged.
	after, err := os.ReadFile(metaPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(before) {
		t.Fatalf("metadata was modified by dry-run:\nbefore: %s\nafter:  %s", before, after)
	}

	// Dry-run output must still contain the expected sections.
	got := out.String()
	for _, want := range []string{
		"metadata:",
		"  .agents/ahm.json",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("dry-run output missing %q:\n%s", want, got)
		}
	}
}

func TestInstallWritesExpectedScaffoldOutput(t *testing.T) {
	root := t.TempDir()
	stdout, stderr, code := runCLI(t, "--root", root, "init")
	if code != 0 {
		t.Fatalf("exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"created:",
		"  AGENTS.md",
		"  .agents/DOCS.md",
		"  .agents/TASKS.md",
		"  .agents/skills/preflight/SKILL.md",
		"  docs/adr/README.md",
	)

	assertFileContainsAll(t, filepath.Join(root, ".agents", "ahm.json"),
		`"version": "`+templates.Version+`"`,
		`".agents/DOCS.md":`,
		`".agents/TASKS.md":`,
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", ".tasks", "index.md"),
		"# Task Index",
		"- Pending: 0",
		"## Next Ready Queue",
		"None.",
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", ".research", "index.md"),
		"# Research Index",
		"This file is generated by `ahm index`.",
		"No inbox research documents yet.",
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", "exec-plans", "active", "index.md"),
		"# Active ExecPlans",
		"This file is generated by `ahm index`.",
		"No active ExecPlans yet.",
	)
}

func TestInstallNeverOverwritesExistingAgentsEntrypoint(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "AGENTS.md"), "# Project Agent Instructions\n\nKeep this.\n")

	stdout, stderr, code := runCLI(t, "--root", root, "--force", "init")
	if code != 0 {
		t.Fatalf("exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout, "skipped:", "  AGENTS.md")
	assertFileContainsAll(t, filepath.Join(root, "AGENTS.md"), "Keep this.")

	meta, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := meta.Files["AGENTS.md"]; ok {
		t.Fatal("AGENTS.md should not be recorded as a managed file")
	}
}

func TestUpgradeDecisions(t *testing.T) {
	root := t.TempDir()
	meta := metadata{
		Version: "0.0.1",
		Files: map[string]string{
			"AGENTS.md":                             hashBytes([]byte("old managed agents\n")),
			".agents/TASKS.md":                      hashBytes([]byte("old managed tasks\n")),
			".agents/PLANS.md":                      hashBytes(templateBytes(t, "workflow/PLANS.md")),
			".agents/RESEARCH.md":                   hashBytes([]byte("locally changed research\n")),
			".agents/DOCS.md":                       hashBytes([]byte("old managed docs\n")),
			".agents/.tasks/README.md":              hashBytes([]byte("old managed tasks readme\n")),
			".agents/.research/README.md":           hashBytes([]byte("old managed research readme\n")),
			".agents/.research/index.md":            hashBytes([]byte("old managed research index\n")),
			".agents/exec-plans/active/index.md":    hashBytes([]byte("old active plan index\n")),
			".agents/exec-plans/completed/index.md": hashBytes([]byte("old completed plan index\n")),
			"docs/adr/README.md":                    hashBytes([]byte("old managed adr\n")),
			".agents/skills/preflight/SKILL.md":     hashBytes([]byte("old managed skill\n")),
		},
	}
	for target := range meta.Files {
		content := "old managed\n"
		switch target {
		case "AGENTS.md":
			content = "old managed agents\n"
		case ".agents/TASKS.md":
			content = "old managed tasks\n"
		case ".agents/PLANS.md":
			content = string(templateBytes(t, "workflow/PLANS.md"))
		case ".agents/RESEARCH.md":
			content = "local edit that should conflict\n"
		case ".agents/DOCS.md":
			content = "old managed docs\n"
		case ".agents/.tasks/README.md":
			content = "old managed tasks readme\n"
		case ".agents/.research/README.md":
			content = "old managed research readme\n"
		case ".agents/.research/index.md":
			content = "old managed research index\n"
		case ".agents/exec-plans/active/index.md":
			content = "locally edited active plan index\n"
		case ".agents/exec-plans/completed/index.md":
			content = "locally edited completed plan index\n"
		case "docs/adr/README.md":
			content = "old managed adr\n"
		case ".agents/skills/preflight/SKILL.md":
			content = "old managed skill\n"
		}
		writeFile(t, filepath.Join(root, target), content)
	}
	if err := writeMetadata(root, meta); err != nil {
		t.Fatal(err)
	}

	var out strings.Builder
	a := app{opts: options{root: root}, out: &out}
	if err := a.install(true); err != nil {
		t.Fatal(err)
	}
	got := out.String()
	assertContainsAll(t, got,
		"skipped:",
		"  AGENTS.md",
		"  .agents/DOCS.md",
		"  .agents/PLANS.md",
		"conflicts:",
		"  .agents/RESEARCH.md",
	)

	after, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if after.Version != templates.Version {
		t.Fatalf("metadata version = %q, want %q (version advances despite conflicts)", after.Version, templates.Version)
	}
	for _, target := range []string{
		".agents/.research/index.md",
		".agents/exec-plans/active/index.md",
		".agents/exec-plans/completed/index.md",
	} {
		if _, ok := after.Files[target]; ok {
			t.Fatalf("%s should not remain in metadata", target)
		}
	}
	assertFileContainsAll(t, filepath.Join(root, ".agents", ".research", "index.md"),
		"# Research Index",
		"This file is generated by `ahm index`.",
	)

	var forceOut strings.Builder
	forced := app{opts: options{root: root, force: true}, out: &forceOut}
	if err := forced.install(true); err != nil {
		t.Fatal(err)
	}
	assertContainsAll(t, forceOut.String(), "updated:", "  .agents/RESEARCH.md")
	assertFileContainsAll(t, filepath.Join(root, "AGENTS.md"), "old managed agents")
	afterForce, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if afterForce.Version != templates.Version {
		t.Fatalf("forced metadata version = %q, want %q", afterForce.Version, templates.Version)
	}
}

func TestUpgradeRemovesObsoleteManagedSkill(t *testing.T) {
	root := t.TempDir()
	oldTarget := ".agents/skills/deslop/SKILL.md"
	oldContent := []byte("old managed skill\n")
	meta := metadata{
		Version: "0.2.0",
		Files: map[string]string{
			oldTarget: hashBytes(oldContent),
		},
	}
	writeFile(t, filepath.Join(root, oldTarget), string(oldContent))
	if err := writeMetadata(root, meta); err != nil {
		t.Fatal(err)
	}

	var out strings.Builder
	a := app{opts: options{root: root}, out: &out}
	if err := a.install(true); err != nil {
		t.Fatal(err)
	}

	assertContainsAll(t, out.String(),
		"removed:",
		"  .agents/skills/deslop/SKILL.md",
		"created:",
		"  .agents/skills/preflight/SKILL.md",
	)
	if _, err := os.Stat(filepath.Join(root, oldTarget)); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("obsolete skill file should be removed, err = %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".agents", "skills", "deslop")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("obsolete skill directory should be removed when empty, err = %v", err)
	}
	assertFileContainsAll(t, filepath.Join(root, ".agents", "skills", "preflight", "SKILL.md"), "name: preflight")

	after, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := after.Files[oldTarget]; ok {
		t.Fatal("obsolete skill should not remain in metadata")
	}
	if _, ok := after.Files[".agents/skills/preflight/SKILL.md"]; !ok {
		t.Fatal("preflight skill should be tracked in metadata")
	}
}

func TestUpgradePreservesModifiedObsoleteManagedSkillAsConflict(t *testing.T) {
	root := t.TempDir()
	oldTarget := ".agents/skills/deslop/SKILL.md"
	oldContent := []byte("old managed skill\n")
	localContent := "locally modified skill\n"
	meta := metadata{
		Version: "0.2.0",
		Files: map[string]string{
			oldTarget: hashBytes(oldContent),
		},
	}
	writeFile(t, filepath.Join(root, oldTarget), localContent)
	if err := writeMetadata(root, meta); err != nil {
		t.Fatal(err)
	}

	var out strings.Builder
	a := app{opts: options{root: root}, out: &out}
	if err := a.install(true); err != nil {
		t.Fatal(err)
	}

	assertContainsAll(t, out.String(),
		"conflicts:",
		"  .agents/skills/deslop/SKILL.md",
		"created:",
		"  .agents/skills/preflight/SKILL.md",
	)
	assertFileContainsAll(t, filepath.Join(root, oldTarget), localContent)
	after, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if after.Files[oldTarget] != hashBytes(oldContent) {
		t.Fatal("modified obsolete skill metadata should be preserved for conflict reporting")
	}
}

func TestInstallAdoptsUntrackedManagedFileWhenContentMatches(t *testing.T) {
	root := t.TempDir()
	tmpl := string(templateBytes(t, "workflow/TASKS.md"))
	// Write a managed file exactly matching the template, but without metadata.
	writeFile(t, filepath.Join(root, ".agents", "TASKS.md"), tmpl)

	var out strings.Builder
	a := app{opts: options{root: root}, out: &out}
	if err := a.install(false); err != nil {
		t.Fatal(err)
	}
	got := out.String()
	assertContainsAll(t, got,
		"adopted:",
		"  .agents/TASKS.md",
	)

	meta, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := meta.Files[".agents/TASKS.md"]; !ok {
		t.Fatal("expected .agents/TASKS.md to be recorded in metadata after adoption")
	}
	content, err := os.ReadFile(filepath.Join(root, ".agents", "TASKS.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != tmpl {
		t.Fatalf("file content was modified; expected original template content")
	}
}

func TestInstallAdoptsUntrackedManagedFileOnUpgrade(t *testing.T) {
	root := t.TempDir()
	tmpl := string(templateBytes(t, "workflow/TASKS.md"))
	// Write a managed file exactly matching the template, but without metadata.
	writeFile(t, filepath.Join(root, ".agents", "TASKS.md"), tmpl)

	var out strings.Builder
	a := app{opts: options{root: root}, out: &out}
	if err := a.install(true); err != nil {
		t.Fatal(err)
	}
	got := out.String()
	assertContainsAll(t, got,
		"adopted:",
		"  .agents/TASKS.md",
	)

	meta, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := meta.Files[".agents/TASKS.md"]; !ok {
		t.Fatal("expected .agents/TASKS.md to be recorded in metadata after adoption")
	}
}

func TestInstallReportsUntrackedManagedFileAsConflictWhenContentDiffers(t *testing.T) {
	root := t.TempDir()
	// Write a managed file with different content than the template, without metadata.
	writeFile(t, filepath.Join(root, ".agents", "TASKS.md"), "# Locally modified\n")

	var out strings.Builder
	a := app{opts: options{root: root}, out: &out}
	if err := a.install(false); err != nil {
		t.Fatal(err)
	}
	got := out.String()
	assertContainsAll(t, got,
		"conflicts:",
		"  .agents/TASKS.md",
	)
	assertNotContains(t, got, "adopted:")

	// File should not be tracked in metadata.
	meta, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := meta.Files[".agents/TASKS.md"]; ok {
		t.Fatal("expected .agents/TASKS.md NOT to be recorded in metadata after conflict")
	}
	// File content should be preserved.
	content, err := os.ReadFile(filepath.Join(root, ".agents", "TASKS.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != "# Locally modified\n" {
		t.Fatalf("file content was overwritten; expected original content")
	}
}

func TestInstallDryRunShowsAdoptedSection(t *testing.T) {
	root := t.TempDir()
	tmpl := string(templateBytes(t, "workflow/TASKS.md"))
	// Write a managed file exactly matching the template, but without metadata.
	writeFile(t, filepath.Join(root, ".agents", "TASKS.md"), tmpl)

	var out strings.Builder
	a := app{opts: options{root: root, dryRun: true}, out: &out}
	if err := a.install(false); err != nil {
		t.Fatal(err)
	}
	got := out.String()
	assertContainsAll(t, got,
		"adopted:",
		"  .agents/TASKS.md",
	)
	// Dry run should not write metadata.
	if _, err := os.Stat(filepath.Join(root, ".agents", "ahm.json")); !errors.Is(err, os.ErrNotExist) {
		t.Fatal("dry-run should not write metadata")
	}
}

func TestInstallForceOverwritesUntrackedManagedFile(t *testing.T) {
	root := t.TempDir()
	// Write a managed file with different content than the template, without metadata.
	writeFile(t, filepath.Join(root, ".agents", "TASKS.md"), "# Locally modified\n")

	var out strings.Builder
	a := app{opts: options{root: root, force: true}, out: &out}
	if err := a.install(false); err != nil {
		t.Fatal(err)
	}
	got := out.String()
	assertContainsAll(t, got,
		"updated:",
		"  .agents/TASKS.md",
	)
	assertNotContains(t, got, "adopted:")
	assertNotContains(t, got, "conflicts:")

	// File should be tracked in metadata after force overwrite.
	meta, err := readMetadata(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := meta.Files[".agents/TASKS.md"]; !ok {
		t.Fatal("expected .agents/TASKS.md to be recorded in metadata after force")
	}
	// File content should now match the template.
	content, err := os.ReadFile(filepath.Join(root, ".agents", "TASKS.md"))
	if err != nil {
		t.Fatal(err)
	}
	tmpl := string(templateBytes(t, "workflow/TASKS.md"))
	if string(content) != tmpl {
		t.Fatalf("file content was not overwritten by --force")
	}
}

func TestMainUpgradeIntegration(t *testing.T) {
	root := t.TempDir()
	stdout, stderr, code := runCLI(t, "--root", root, "init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	stdout, stderr, code = runCLI(t, "--root", root, "upgrade")
	if code != 0 {
		t.Fatalf("upgrade exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	assertContainsAll(t, stdout,
		"skipped:",
		"  AGENTS.md",
		"  .agents/TASKS.md",
	)
	assertFileContainsAll(t, filepath.Join(root, ".agents", "ahm.json"), `"version": "`+templates.Version+`"`)
}

func TestInstallFailsOnCorruptMetadata(t *testing.T) {
	root := t.TempDir()
	// Init first to create valid metadata.
	stdout, stderr, code := runCLI(t, "--root", root, "init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Corrupt the metadata file.
	metaPath := filepath.Join(root, ".agents", "ahm.json")
	if err := os.WriteFile(metaPath, []byte("{invalid json}"), 0o644); err != nil {
		t.Fatal(err)
	}

	// init should fail with a clear error about corrupt metadata.
	stdout, stderr, code = runCLI(t, "--root", root, "init")
	if code == 0 {
		t.Fatalf("expected init to fail on corrupt metadata, stdout = %s", stdout)
	}
	assertContainsAll(t, stderr, "corrupt workflow metadata .agents/ahm.json")
}

func TestUpgradeFailsOnCorruptMetadata(t *testing.T) {
	root := t.TempDir()
	// Init first to create valid metadata.
	stdout, stderr, code := runCLI(t, "--root", root, "init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}

	// Corrupt the metadata file.
	metaPath := filepath.Join(root, ".agents", "ahm.json")
	if err := os.WriteFile(metaPath, []byte("{invalid json}"), 0o644); err != nil {
		t.Fatal(err)
	}

	// upgrade should fail with a clear error about corrupt metadata.
	stdout, stderr, code = runCLI(t, "--root", root, "upgrade")
	if code == 0 {
		t.Fatalf("expected upgrade to fail on corrupt metadata, stdout = %s", stdout)
	}
	assertContainsAll(t, stderr, "corrupt workflow metadata .agents/ahm.json")
}

func TestInstallSucceedsWithMissingMetadata(t *testing.T) {
	root := t.TempDir()
	// No prior init, no metadata. Should succeed as a fresh install.
	stdout, stderr, code := runCLI(t, "--root", root, "init")
	if code != 0 {
		t.Fatalf("init exit code = %d, stdout = %s, stderr = %s", code, stdout, stderr)
	}
	assertContainsAll(t, stdout, "created:")
}
