package ahm

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// primeTestRoots is a testing helper that sets up a committed-mode repo for prime tests.
func newCommittedModeRepoWithMultipleTasks(t *testing.T, taskCount int) string {
	t.Helper()
	root := newGitRepo(t)
	writeAHMConfig(t, root)
	writeFile(t, filepath.Join(root, ".ahm", ".gitignore"),
		recordsGitignoreHeader+strings.Join(recordsGitignoreEntries, "\n")+"\n")
	for i := 1; i <= taskCount; i++ {
		id := fmt.Sprintf("%03d", i)
		writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", id+".md"), id, "Task "+id, "Pending", "depends_on: -\n")
	}
	// docs/adr/index.md stays committed (project-facing documentation).
	// Content must match what renderADRIndex([]ADR{}) produces so prime
	// does not rewrite it as a modified tracked file.
	writeFile(t, filepath.Join(root, "docs", "adr", "index.md"), "# ADR Index\n\nThis file is generated by `ahm index`. Do not edit it by hand.\n\n| ADR | Title | Status | Date |\n| --- | ----- | ------ | ---- |\n")
	git(t, root, "add", ".ahm", "docs")
	git(t, root, "commit", "-q", "-m", "add committed workflow records")
	return root
}

func TestPrimePrintsSessionBriefing(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "001.md"), "001", "Current Work", "In Progress", "depends_on: -\n")
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "002.md"), "002", "Ready Work", "Pending", "depends_on: -\n")
	indexer := app{opts: options{root: root}, out: &strings.Builder{}}
	if err := indexer.writeIndexes(); err != nil {
		t.Fatal(err)
	}

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"root: "+root,
		"workflow: installed dev",
		"validation: ok",
		"## In Progress",
		"001 [In Progress] P2 S Current Work",
		"## Ready",
		"002 [Pending] P2 S Ready Work",
		"Blocked: 0",
		"Open: 0",
	)
	// Task 264c: prime is pure state. It reports counts and findings and
	// names no command to run and no workflow step.
	assertNotContains(t, stdout,
		"# Dirty Worktree",
		"## Managed Work Intake",
		"## Useful Commands",
		"ahm context",
		"ahm doctor",
		"ahm task ready",
		"ahm task blocked",
		"ahm task list",
	)
}

func TestPrimeJSONOutput(t *testing.T) {
	root := projectRoot(t)
	var installOut strings.Builder
	installer := app{opts: options{root: root}, out: &installOut}
	if err := installer.install(); err != nil {
		t.Fatal(err)
	}

	stdout, stderr, code := runCLI(t, "--root", root, "--json", "prime")
	if code != 0 {
		t.Fatalf("prime --json exit code = %d, stderr = %s", code, stderr)
	}
	// The emitted JSON escapes path separators (backslashes on Windows), so
	// the expectation must use the same encoding as json.MarshalIndent.
	rootJSON, err := json.Marshal(root)
	if err != nil {
		t.Fatal(err)
	}
	assertContainsAll(t, stdout,
		`"root": `+string(rootJSON),
		`"in_progress":`,
		`"ready":`,
		`"ready_total":`,
		`"blocked":`,
		`"open":`,
	)
	assertNotContains(t, stdout, `"instructions"`)
	assertNotContains(t, stdout, `"records"`)
	// The procedure channel is gone: no command list, no routing paths.
	assertNotContains(t, stdout, `"commands"`, `"paths"`)
}

func TestPrimePlainOutput(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "001.md"), "001", "Test Task", "Pending", "depends_on: -\n")

	stdout, stderr, code := runCLI(t, "--root", root, "--plain", "prime")
	if code != 0 {
		t.Fatalf("prime --plain exit code = %d, stderr = %s", code, stderr)
	}
	// Compact JSON should be a single line
	if strings.Count(stdout, "\n") > 2 {
		t.Fatalf("plain output should be compact JSON (single line), got %d lines:\n%s", strings.Count(stdout, "\n"), stdout)
	}
	// Compact JSON escapes path separators (backslashes on Windows), so the
	// expectation must use the same encoding as json.Marshal.
	rootJSON, err := json.Marshal(root)
	if err != nil {
		t.Fatal(err)
	}
	assertContainsAll(t, stdout, `"root":`+string(rootJSON), `"ready_total":`)
	assertNotContains(t, stdout, `"records"`)
}

func TestPrimeReadyCapWithOverflow(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	// Create 7 ready tasks — only 5 should display with overflow pointer
	for i := 1; i <= 7; i++ {
		id := fmt.Sprintf("%03d", i)
		writeTaskFileWithPriority(t, filepath.Join(root, ".ahm", "tasks", "active", id+".md"), id, "Ready Task "+id, "Pending", "P2", "depends_on: -\n")
	}
	indexer := app{opts: options{root: root}, out: &strings.Builder{}}
	if err := indexer.writeIndexes(); err != nil {
		t.Fatal(err)
	}

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"2 more ready",
	)
	assertNotContains(t, stdout, "ahm task ready")
	// Count ready task lines (lines like "001 [Pending] P2 S Ready Task 001")
	readyLines := 0
	for _, line := range strings.Split(stdout, "\n") {
		if strings.Contains(line, "[Pending]") && strings.Contains(line, "Ready Task") {
			readyLines++
		}
	}
	if readyLines != 5 {
		t.Fatalf("expected 5 ready task lines, got %d", readyLines)
	}
}

// TestPrimeOmitsRetiredRecordFamilies pins acceptance criterion four of task
// 264b: prime's briefing no longer has an ExecPlan or research section, even
// when those trees still hold records.
func TestPrimeOmitsRetiredRecordFamilies(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	writeFile(t, filepath.Join(root, ".ahm", "research", "topics", "note.md"), "# Topic Note\n")
	writeFile(t, filepath.Join(root, ".ahm", "exec-plans", "active", "plan.md"), "# Plan\n")

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertNotContains(t, stdout, "## Active ExecPlans", "## Recent Research")

	stdout, stderr, code = runCLI(t, "--root", root, "--json", "prime")
	if code != 0 {
		t.Fatalf("prime --json exit code = %d, stderr = %s", code, stderr)
	}
	assertNotContains(t, stdout, `"plans"`, `"research"`)
}

func TestPrimeDirtyWorktreeWarning(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	root := t.TempDir()
	if out, err := exec.Command("git", "-C", root, "init", "-q").CombinedOutput(); err != nil {
		t.Fatalf("git init: %v: %s", err, out)
	}
	// Create and track a file, then make it dirty
	writeFile(t, filepath.Join(root, "tracked.txt"), "clean\n")
	if out, err := exec.Command("git", "-C", root, "add", "tracked.txt").CombinedOutput(); err != nil {
		t.Fatalf("git add: %v: %s", err, out)
	}
	// CI runners have no git identity configured; set one for this repo so the
	// commit succeeds everywhere.
	if out, err := exec.Command("git", "-C", root, "-c", "user.name=Test User", "-c", "user.email=test@example.com", "commit", "-m", "initial", "--allow-empty").CombinedOutput(); err != nil {
		t.Fatalf("git commit: %v: %s", err, out)
	}
	// Now dirty the tracked file
	writeFile(t, filepath.Join(root, "tracked.txt"), "dirty\n")

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"# Dirty Worktree",
		"The working directory has uncommitted changes",
	)
	// Task 264c: the warning reports state only; it prescribes no step.
	assertNotContains(t, stdout, "Resolve them before starting new work")
}

func TestPrimeNoDirtyWarningOnCleanTree(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	root := t.TempDir()
	if out, err := exec.Command("git", "-C", root, "init", "-q").CombinedOutput(); err != nil {
		t.Fatalf("git init: %v: %s", err, out)
	}

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertNotContains(t, stdout, "# Dirty Worktree")
}

func TestPrimeNoWrites(t *testing.T) {
	root := projectRoot(t)
	var installOut strings.Builder
	installer := app{opts: options{root: root}, out: &installOut}
	if err := installer.install(); err != nil {
		t.Fatal(err)
	}

	// Capture the file tree before prime
	var beforeFiles []string
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			beforeFiles = append(beforeFiles, path)
		}
		return nil
	}); err != nil {
		t.Fatalf("walk before prime: %v", err)
	}

	_, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}

	// Check file tree after prime
	var afterFiles []string
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			afterFiles = append(afterFiles, path)
		}
		return nil
	}); err != nil {
		t.Fatalf("walk after prime: %v", err)
	}

	if len(beforeFiles) != len(afterFiles) {
		t.Fatalf("prime created or removed files: before=%d, after=%d", len(beforeFiles), len(afterFiles))
	}
}

func TestPrimeReportsValidationFindingsWithoutFailing(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "001.md"), "001", "Missing Dependency", "Pending", "depends_on: 999\n")

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"validation:",
		"task_dependency_missing",
		"task 001 depends on missing task 999",
	)
	assertNotContains(t, stdout, "ahm doctor")
}

func TestPrimeWarnsWhenMissingMetadataFallbackSkipsMalformedTasks(t *testing.T) {
	setStoreHome(t)
	// A repository with no configuration is a new project, so its records live in
	// the store; metadata is missing all the same.
	root := t.TempDir()
	writeFile(t, storeTaskFile(t, root, "active", "001"), "---\nbad key: value\n---\n# Broken Task\n")

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"metadata_missing",
		"task_malformed",
	)
	assertContainsAll(t, stderr, "warning: some task files could not be parsed and were skipped")
	if count := strings.Count(stderr, "warning: some task files could not be parsed and were skipped"); count != 1 {
		t.Fatalf("warning count = %d, stderr = %s", count, stderr)
	}
}

func TestPrimeWarningsOnlyValidationDisplay(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	// A Completed task in the active bucket yields a warning with no errors.
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "001.md"), "001", "Bucket Mismatch", "Completed", "")

	var indexOut strings.Builder
	indexer := app{opts: options{root: root}, out: &indexOut}
	if err := indexer.writeIndexes(); err != nil {
		t.Fatal(err)
	}

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"validation: 1 errors, 2 warnings",
		"task_bucket_mismatch",
	)
	assertNotContains(t, stdout, "validation: ok", "ahm doctor")

	jsonOut, stderr, code := runCLI(t, "--root", root, "--json", "prime")
	if code != 0 {
		t.Fatalf("prime --json exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, jsonOut, `"validation_ok": false`)
}

func TestReadGitContextReportsDirtyWorktree(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	root := t.TempDir()
	if out, err := exec.Command("git", "-C", root, "init", "-q").CombinedOutput(); err != nil {
		t.Fatalf("git init: %v: %s", err, out)
	}
	writeFile(t, filepath.Join(root, "tracked.txt"), "dirty\n")

	info := readGitContext(root)
	if !info.Available {
		t.Fatal("expected git to be available")
	}
	if info.Error != "" {
		t.Fatalf("unexpected git error: %s", info.Error)
	}
	if !info.Dirty || info.Changes == 0 {
		t.Fatalf("expected dirty worktree, got %#v", info)
	}
}

func TestPrimeShowsReadyOnlyWhenTasksExist(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	// Only a non-ready task (Completed)
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "001.md"), "001", "Done Work", "Completed", "depends_on: -\n")
	indexer := app{opts: options{root: root}, out: &strings.Builder{}}
	if err := indexer.writeIndexes(); err != nil {
		t.Fatal(err)
	}

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertNotContains(t, stdout, "## Ready")
}

func TestPrimeShowsInProgressOnlyWhenTasksExist(t *testing.T) {
	root := t.TempDir()
	setupAhmRepo(t, root)
	// Only ready tasks, no in-progress
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "001.md"), "001", "Ready Work", "Pending", "depends_on: -\n")
	indexer := app{opts: options{root: root}, out: &strings.Builder{}}
	if err := indexer.writeIndexes(); err != nil {
		t.Fatal(err)
	}

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertNotContains(t, stdout, "## In Progress")
	assertContainsAll(t, stdout, "## Ready")
}

// -------- Committed-mode regression tests --------

func TestPrimeInCommittedModeShowsTaskBriefing(t *testing.T) {
	root := newCommittedModeRepoWithMultipleTasks(t, 2)

	stdout, stderr, code := runCLI(t, "--root", root, "prime")
	if code != 0 {
		t.Fatalf("prime exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout,
		"root: "+root,
		"workflow: installed",
		"validation: ok",
		"## Ready",
		"001 [Pending]",
		"002 [Pending]",
	)
	assertNotContains(t, stdout, "# Dirty Worktree", "## Managed Work Intake")
}

func TestPrimeInCommittedModeRegeneratesStaleIndexes(t *testing.T) {
	root := newCommittedModeRepoWithMultipleTasks(t, 2)

	// Run prime first to generate indexes.
	if _, stderr, code := runCLI(t, "--root", root, "prime"); code != 0 {
		t.Fatalf("first prime failed: %s", stderr)
	}

	taskIndex := filepath.Join(root, ".ahm", "tasks", "active", "index.md")
	if _, err := os.Stat(taskIndex); err != nil {
		t.Fatalf("task index not generated: %v", err)
	}

	// Stale the generated index.
	if err := os.WriteFile(taskIndex, []byte("# Stale Index\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// prime should regenerate the stale index.
	if _, stderr, code := runCLI(t, "--root", root, "prime"); code != 0 {
		t.Fatalf("prime after stale index failed: %s", stderr)
	}
	assertFileContainsAll(t, taskIndex, "# Active Tasks", "001")
}

func TestPrimeInCommittedModePreservesGitState(t *testing.T) {
	root := newCommittedModeRepoWithMultipleTasks(t, 1)
	headBefore := strings.TrimSpace(git(t, root, "rev-parse", "HEAD"))
	configFile := filepath.Join(root, ".ahm", "config.json")
	configBefore := mustRead(t, configFile)

	if _, stderr, code := runCLI(t, "--root", root, "prime"); code != 0 {
		t.Fatalf("prime failed: %s", stderr)
	}

	// HEAD unchanged.
	if got := strings.TrimSpace(git(t, root, "rev-parse", "HEAD")); got != headBefore {
		t.Fatalf("prime moved HEAD from %s to %s", headBefore, got)
	}
	// Nothing staged.
	if staged := strings.TrimSpace(git(t, root, "diff", "--cached", "--name-only")); staged != "" {
		t.Fatalf("prime staged changes:\n%s", staged)
	}
	// Config file unchanged (byte-identical before and after prime).
	if got := mustRead(t, configFile); got != configBefore {
		t.Fatalf("prime modified config.json: before=%q after=%q", configBefore, got)
	}
	assertNotContains(t, configBefore, "records_last_sync")
	assertNotContains(t, mustRead(t, configFile), "records_last_sync")
}

func TestPrimeInCommittedModeDryRunDoesNotWrite(t *testing.T) {
	root := newCommittedModeRepoWithMultipleTasks(t, 1)

	// First run prime (non-dry-run) to generate all expected indexes.
	if _, stderr, code := runCLI(t, "--root", root, "prime"); code != 0 {
		t.Fatalf("first prime failed: %s", stderr)
	}

	// Stale the active task index.
	taskIndex := filepath.Join(root, ".ahm", "tasks", "active", "index.md")
	writeFile(t, taskIndex, "# Stale Index\n")

	// Dry-run prime must not regenerate the stale index.
	stdout, stderr, code := runCLI(t, "--root", root, "--dry-run", "prime")
	if code != 0 {
		t.Fatalf("prime --dry-run exit code = %d, stderr = %s", code, stderr)
	}
	assertContainsAll(t, stdout, "root: "+root, "## Ready")
	assertFileContainsAll(t, taskIndex, "Stale Index")
}

func TestIndexInCommittedModePreservesGitState(t *testing.T) {
	root := newCommittedModeRepoWithMultipleTasks(t, 1)
	headBefore := strings.TrimSpace(git(t, root, "rev-parse", "HEAD"))

	// Run index to generate indexes.
	if _, stderr, code := runCLI(t, "--root", root, "index"); code != 0 {
		t.Fatalf("index failed: %s", stderr)
	}

	// HEAD unchanged.
	if got := strings.TrimSpace(git(t, root, "rev-parse", "HEAD")); got != headBefore {
		t.Fatalf("index moved HEAD from %s to %s", headBefore, got)
	}
	// Nothing staged.
	if staged := strings.TrimSpace(git(t, root, "diff", "--cached", "--name-only")); staged != "" {
		t.Fatalf("index staged changes:\n%s", staged)
	}
}

func TestStatusInCommittedModePreservesGitState(t *testing.T) {
	root := newCommittedModeRepoWithMultipleTasks(t, 2)

	// First run index to regenerate expected indexes so status doesn't exit 1.
	if _, stderr, code := runCLI(t, "--root", root, "index"); code != 0 {
		t.Fatalf("index failed: %s", stderr)
	}

	headBefore := strings.TrimSpace(git(t, root, "rev-parse", "HEAD"))

	if _, stderr, code := runCLI(t, "--root", root, "status"); code != 0 {
		t.Fatalf("status exit code = %d, stderr = %s", code, stderr)
	}

	// HEAD unchanged.
	if got := strings.TrimSpace(git(t, root, "rev-parse", "HEAD")); got != headBefore {
		t.Fatalf("status moved HEAD from %s to %s", headBefore, got)
	}
	// Worktree is clean (no untracked or modified files from status).
	if out := strings.TrimSpace(git(t, root, "status", "--porcelain")); out != "" {
		t.Fatalf("status left dirty worktree:\n%s", out)
	}
}

func TestBranchCheckoutRegeneratesIndexes(t *testing.T) {
	// Start with a committed-mode repo on main.
	root := newCommittedModeRepoWithMultipleTasks(t, 2)

	// Create a branch with different tasks.
	git(t, root, "checkout", "-q", "-b", "feature-a")
	// Add a third task on this branch.
	writeTaskFile(t, filepath.Join(root, ".ahm", "tasks", "active", "003.md"), "003", "Feature A Work", "Pending", "depends_on: -\n")
	git(t, root, "add", ".ahm/tasks/active/003.md")
	git(t, root, "commit", "-q", "-m", "add feature-a task")

	// Go back to main, run prime, verify index shows only 2 tasks.
	git(t, root, "checkout", "-q", "main")
	// Run prime to regenerate indexes.
	if _, stderr, code := runCLI(t, "--root", root, "prime"); code != 0 {
		t.Fatalf("prime on main failed: %s", stderr)
	}
	taskIndex := filepath.Join(root, ".ahm", "tasks", "active", "index.md")
	assertFileContainsAll(t, taskIndex, "# Active Tasks")
	assertFileContainsAll(t, taskIndex, "001")
	assertFileContainsAll(t, taskIndex, "002")
	assertNotContains(t, mustRead(t, taskIndex), "003")

	// Switch to feature-a, run prime, verify index now shows 3 tasks with 003.
	git(t, root, "checkout", "-q", "feature-a")
	// Stale the index that prime will regenerate.
	writeFile(t, taskIndex, "# Stale\n")
	if _, stderr, code := runCLI(t, "--root", root, "prime"); code != 0 {
		t.Fatalf("prime on feature-a failed: %s", stderr)
	}
	assertFileContainsAll(t, taskIndex, "003")
}
